import { ObjectId } from "mongodb";
export type IdentityProviderFromDb = {
  _id: ObjectId;
  uid: string;
  name: string;
  active: boolean;
  title: string;
  url: string;
  statusURL: string;
  authzURL?: string;
  tokenURL?: string;
  userInfoURL?: string;
  endSessionURL: string;
  discoveryUrl?: string;
  discovery: boolean;
  jwksURL?: string;
  clientID: string;
  client_secret: string;
  createdAt: Date;
  updatedAt: Date;
  updatedBy: string;
  userinfo_encrypted_response_enc?: string;
  userinfo_encrypted_response_alg?: string;
  userinfo_signed_response_alg?: "RS256" | "ES256" | "HS256" | "";
  id_token_signed_response_alg?: "RS256" | "ES256" | "HS256";
  id_token_encrypted_response_alg?: string;
  id_token_encrypted_response_enc?: string;
  token_endpoint_auth_method?: string;
  siret: string;
  supportEmail?: string;
  isRoutingEnabled: boolean;
  fqdns: string[];
};
