import { ObjectId } from "mongodb";
export type ServiceProviderFromDb = {
  _id: ObjectId;
  title: string;
  name: string;
  active: boolean;
  type: string;
  IPServerAddressesAndRanges: string[];
  email: string;
  redirect_uris: string[];
  post_logout_redirect_uris: string[];
  secretCreatedAt: Date;
  createdAt: Date;
  updatedAt?: Date;
  updatedBy: string;
  key: string;
  client_secret: string;
  secretUpdatedAt?: Date;
  secretUpdatedBy?: string;
  scopes: string[];
  userinfo_signed_response_alg?: string;
  id_token_signed_response_alg?: string;
  introspection_signed_response_alg?: string | null;
  introspection_encrypted_response_alg?: string | null;
  introspection_encrypted_response_enc?: string | null;
  response_types?: string[] | null;
  grant_types?: string[] | null;
  jwks_uri: string;
};
